apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{ template "app.labels" }}
  name: {{ .Values.db.name | default "gitea-db" | quote }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.size | default "1Gi" | quote }}
